<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>自定义promise</title>
</head>
<body>
    <script src="./lib/promise.js"></script>
    <script>
        // 只有抛出异常或者返回失败的promise才会执行reject函数
        console.log("开始执行html");
        console.log(Promise);
        const p = new Promise((resolve,reject)=>{
            setTimeout(()=>{
                // resolve(1)
                console.log("resolve");
                reject(2)
            },100)
        }).then(
            value =>{
                console.log('onResolved1()',value);
            },
            reason =>{
                console.log('onRejected1()',reason);
                throw 3
            },
        ).then(
            value =>{
                console.log('onResolved2()',value);
            },
            reason =>{
                console.log('onRejected2()',reason);
                throw 5
            },
        ).catch(reason=>{
            console.log('onRejected3()',reason);
        })
    </script>
</body>
</html>